### PR TITLE
[FIX] Fix newline after program with exit code 130

### LINKED ISSUE #257: [BUG] minishell running in minishell prints too many newlines after exiting, also in subshells
This happens when first pressing Ctrl+C and then exiting.
It's because when we print a newline depends on the exit code.

With a program that returns 130 we also print a newline. 
This also applies to subshells. The more nested subshells there are, the more newlines get printed.

It is now very clear that signals should be handled by the main shell process, not from the child processes.

### PR DESCRIPTION
**Pull request by itislu**
- Fixes programs with exit code 130 causing a newline.
- Fixes minishell running in minishell printing too many newlines after SIGINT + exit.
- Fixes nested subshells printing too many newlines: `( ( (cat) ) )`
- Fixes `cat | ./segfault` behavior: `Segmentation fault` only gets printed at end of pipeline.
- This also fixes the exit code affecting `&&`/`|| `: `./return_130 || echo 123` did not print `123`.

- Resolves #257

---

### Known issues

- `(sleep 3 && ./segfault)` should not print `Segmentation fault` (which is super weird bc `(./segfault)` **does** print `Segmentation fault`!
- SIGQUIT behavior in subshells remains unsolved - #206

### CODE REVIEW

**Comment by itislu** [comment]
Something is wrong with the CI shell scripts...

File: source/backend/executor/wait_process.c [hunk 1]
```diff
@@ -29,26 +29,35 @@ bool	wait_process(t_sh *shell, pid_t pid)
 void	wait_all_child_pid(t_sh *shell)
 {
 	t_list	*child_pid_node;
+	int		exit_wstatus;
 	bool	got_sigint;
```
Comment (LeaYeh) [inline source/backend/executor/wait_process.c:33]: Hey I just noticed this var, can we change the got?

File: source/backend/executor/wait_process.c [hunk 2]
```diff
@@ -29,26 +29,35 @@ bool	wait_process(t_sh *shell, pid_t pid)
...
+		wait_child_pid(pid, &got_sigint);
 		child_pid_node = child_pid_node->next;
 	}
 	if (got_sigint)
-		ft_printf("\n");
+		print_error("\n");
+	shell->exit_code = handle_exit_status(exit_wstatus);
+}
+
+static int	wait_child_pid(pid_t pid, bool *got_sigint)
```
Comment (LeaYeh) [inline source/backend/executor/wait_process.c:52]: What make this different than before

**Review by LeaYeh — COMMENTED** [review]
Maybe need to check tomorrow

**Review by LeaYeh — APPROVED** [review]

**Review by LeaYeh — CHANGES_REQUESTED** [review]
I don't see the difference need explanation

**Comment by LeaYeh** [comment]
And I feel sometimes you over norminattee make the code confusing me.
For example, is the wait child pid and different than wait pid? Why need a sub function to take the function jump but not gain any benefit?

**Comment by itislu** [comment]
I'm happy to do a code review on campus whenever you have time!

**Review by LeaYeh — APPROVED** [review]
