### PR TITLE
[FIX] Fix wrong null-expansion after word-splitting and quote combination

### LINKED ISSUE #281: [BUG] Wrong null-expansion after word-splitting and quote combination
Test case 1:
```sh
export A="   a"
echo ""$A
```
Bash:
```sh
 a
```
🌊rash:
```sh
a
```
---
Test case 2:
```sh
export B="b   "
echo ""$B c
```
Bash:
```sh
b c
```
🌊rash:
```sh
b  c
```

### PR DESCRIPTION
**Pull request by itislu**
- [x] First merge #282 
---
The issue was caused by too early quote removal.
Now the quotes get removed at the end of the expansion process, as is specified in the GNU Bash manual as well.

- All expander tasks now have a double pointer to the string saved in the corresponding `lst` node.
- Every entry to the expander now gets put into a `lst` node immediately.
---
* Resolves #281

### CODE REVIEW

File: source/frontend/expander/expander_task_list_utils.c [hunk 1]
```diff
@@ -58,17 +59,26 @@ t_expander_task	*init_expander_task(t_expander_task_type type, int start,
 	}
 	else
 		task->varname = NULL;
-	task->result_len = -1;
+	task->result_len = 0;
```
Comment (itislu) [inline source/frontend/expander/expander_task_list_utils.c:62]: What's better for initting? It should never stay this way anyway...

**Review by LeaYeh — APPROVED** [review]

File: source/frontend/expander/expander_task_list_utils.c (hunk 1 above)
Comment (itislu) [reply source/frontend/expander/expander_task_list_utils.c:62]: * Will change back to `-1` in e946842cb1135e86e3e3f0b36cfc79a87bf2e368 of PR #292.
